products = [
  {
    '_id': '1',
    'name': 'Monday Menu',
    'image': '/images/hmenu01corp.jpg',
    'description': 'Ligero y Saludable, Sin Azúcar',
    'dessert': 'Ice cream',
    'soupOption1': 'Soup 1',
    'soupOption1image': '/images/soup01.jpg',
    'soupOption2': 'Soup 2',
    'soupOption2image': '/images/soup02.jpg',
    'mainFoodOption1': 'Main 1',
    'mainFoodOption1image' : '/images/main01.jpg',
    'mainFoodOption2': 'Main 2',
    'mainFoodOption2image' : '/images/main02.jpg',
    'secondaryFood1': 'Aloz',
    'secondaryFood2': 'Beans',
    'secondaryFood3': 'Mas Aloz',
    'waterOption1': 'Water-1',
    'waterOption2': 'Water-2',
    'bread': 0,
  },
  {
    '_id': '2',
    'name': 'Tuesday Menu',
    'image': '/images/hmenu02corp.jpg',
    'description':
    'Meatless Day, Sin Azúcar',
    'dessert': 'Ice cream',
    'soupOption1': 'Soup 1',
    'soupOption1image': '/images/soup01.jpg',
    'soupOption2': 'Soup 2',
    'soupOption2image': '/images/soup02.jpg',
    'mainFoodOption1': 'Main 1',
    'mainFoodOption1image' : '/images/main01.jpg',
    'mainFoodOption2': 'Main 2',
    'mainFoodOption2image' : '/images/main02.jpg',
    'secondaryFood1': 'Secondary1',
    'secondaryFood2': 'Secondary2',
    'secondaryFood3': 'Secondary3',
    'waterOption1': 'Water-1',
    'waterOption2': 'Water-2',
    'bread': 0,
    
  },
  {
    '_id': '3',
    'name': 'Wednesday Menu',
    'image': '/images/hmenu03corp.jpg',
    'description':
    'Ligero y Saludable, Sin Azúcar',
    'dessert': 'Ice cream',
    'soupOption1': 'Soup 1',
    'soupOption1image': '/images/soup01.jpg',
    'soupOption2': 'Soup 2',
    'soupOption2image': '/images/soup02.jpg',
    'mainFoodOption1': 'Main 1',
    'mainFoodOption1image' : '/images/main01.jpg',
    'mainFoodOption2': 'Main 2',
    'mainFoodOption2image' : '/images/main02.jpg',
    'secondaryFood1': 'Secondary1',
    'secondaryFood2': 'Secondary2',
    'secondaryFood3': 'Secondary3',
    'waterOption1': 'Water-1',
    'waterOption2': 'Water-2',
    'bread': 0,
    
  },
  {
    '_id': '4',
    'name': 'Thursday Menu',
    'image': '/images/hmenu04corp.jpg',
    'description':
    'Ligero y Saludable, Sin Azúcar',
    'dessert': 'Ice cream',
    'soupOption1': 'Soup 1',
    'soupOption1image': '/images/soup01.jpg',
    'soupOption2': 'Soup 2',
    'soupOption2image': '/images/soup02.jpg',
    'mainFoodOption1': 'Main 1',
    'mainFoodOption1image' : '/images/main01.jpg',
    'mainFoodOption2': 'Main 2',
    'mainFoodOption2image' : '/images/main02.jpg',
    'secondaryFood1': 'Secondary1',
    'secondaryFood2': 'Secondary2',
    'secondaryFood3': 'Secondary3',
    'waterOption1': 'Water-1',
    'waterOption2': 'Water-2',
    'bread': 0,
    
  },
  {
    '_id': '5',
    'name': 'Friday Menu',
    'image': '/images/hmenu05corp.jpg',
    'description':
    'Especial, Ligero y Saludable, Sin Azúcar',
    'dessert': 'Ice cream',
    'soupOption1': 'Soup 1',
    'soupOption1image': '/images/soup01.jpg',
    'soupOption2': 'Soup 2',
    'soupOption2image': '/images/soup02.jpg',
    'mainFoodOption1': 'Main 1',
    'mainFoodOption1image' : '/images/main01.jpg',
    'mainFoodOption2': 'Main 2',
    'mainFoodOption2image' : '/images/main02.jpg',
    'secondaryFood1': 'Secondary1',
    'secondaryFood2': 'Secondary2',
    'secondaryFood3': 'Secondary3',
    'waterOption1': 'Water-1',
    'waterOption2': 'Water-2',
    'bread': 0,
    
  },
  {
    '_id': '6',
    'name': ' Saturday Menu',
    'image': '/images/hmenu05corp.jpg',
    'description':
    'Especial, Ligero y Saludable, Sin Azúcar',
    'dessert': 'Ice cream',
    'soupOption1': 'Soup 1',
    'soupOption1image': '/images/soup01.jpg',
    'soupOption2': 'Soup 2',
    'soupOption2image': '/images/soup02.jpg',
    'mainFoodOption1': 'Main 1',
    'mainFoodOption1image' : '/images/main01.jpg',
    'mainFoodOption2': 'Main 2',
    'mainFoodOption2image' : '/images/main02.jpg',
    'secondaryFood1': 'Secondary1',
    'secondaryFood2': 'Secondary2',
    'secondaryFood3': 'Secondary3',
    'waterOption1': 'Water-1',
    'waterOption2': 'Water-2',
    'bread': 0,
  }
]